max_width = 120
use_small_heuristics = "Off"

hard_tabs = false
tab_spaces = 4

fn_call_width = 60
fn_params_layout = "Tall"
fn_args_layout = "Tall"

chain_width = 60
single_line_if_else_max_width = 60

match_block_trailing_comma = true
struct_lit_width = 40
struct_variant_width = 40

reorder_imports = true

newline_style = "Unix"
